//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class AppBudgetService
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int ServiceId
        {
            get { return _serviceId; }
            set
            {
                if (_serviceId != value)
                {
                    if (Service != null && Service.Id != value)
                    {
                        Service = null;
                    }
                    _serviceId = value;
                }
            }
        }
        private int _serviceId;
    
        public virtual int AgencyId
        {
            get { return _agencyId; }
            set
            {
                if (_agencyId != value)
                {
                    if (Agency != null && Agency.Id != value)
                    {
                        Agency = null;
                    }
                    _agencyId = value;
                }
            }
        }
        private int _agencyId;
    
        public virtual int AppBudgetId
        {
            get { return _appBudgetId; }
            set
            {
                if (_appBudgetId != value)
                {
                    if (AppBudget != null && AppBudget.Id != value)
                    {
                        AppBudget = null;
                    }
                    _appBudgetId = value;
                }
            }
        }
        private int _appBudgetId;
    
        public virtual decimal CcGrant
        {
            get;
            set;
        }
    
        public virtual decimal RequiredMatch
        {
            get;
            set;
        }
    
        public virtual decimal AgencyContribution
        {
            get;
            set;
        }
    
        public virtual string Remarks
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> OriginalCcGrant
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<SubReport> SubReports
        {
            get
            {
                if (_subReports == null)
                {
                    var newCollection = new FixupCollection<SubReport>();
                    newCollection.CollectionChanged += FixupSubReports;
                    _subReports = newCollection;
                }
                return _subReports;
            }
            set
            {
                if (!ReferenceEquals(_subReports, value))
                {
                    var previousValue = _subReports as FixupCollection<SubReport>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSubReports;
                    }
                    _subReports = value;
                    var newValue = value as FixupCollection<SubReport>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSubReports;
                    }
                }
            }
        }
        private ICollection<SubReport> _subReports;
    
    	
    	public virtual Agency Agency
        {
            get { return _agency; }
            set
            {
                if (!ReferenceEquals(_agency, value))
                {
                    var previousValue = _agency;
                    _agency = value;
                    FixupAgency(previousValue);
                }
            }
        }
        private Agency _agency;
    
    	
    	public virtual Service Service
        {
            get { return _service; }
            set
            {
                if (!ReferenceEquals(_service, value))
                {
                    var previousValue = _service;
                    _service = value;
                    FixupService(previousValue);
                }
            }
        }
        private Service _service;
    
    	
    	public virtual AppBudget AppBudget
        {
            get { return _appBudget; }
            set
            {
                if (!ReferenceEquals(_appBudget, value))
                {
                    var previousValue = _appBudget;
                    _appBudget = value;
                    FixupAppBudget(previousValue);
                }
            }
        }
        private AppBudget _appBudget;
    
        public virtual ICollection<PersonnelReport> PersonnelReports
        {
            get
            {
                if (_personnelReports == null)
                {
                    var newCollection = new FixupCollection<PersonnelReport>();
                    newCollection.CollectionChanged += FixupPersonnelReports;
                    _personnelReports = newCollection;
                }
                return _personnelReports;
            }
            set
            {
                if (!ReferenceEquals(_personnelReports, value))
                {
                    var previousValue = _personnelReports as FixupCollection<PersonnelReport>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPersonnelReports;
                    }
                    _personnelReports = value;
                    var newValue = value as FixupCollection<PersonnelReport>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPersonnelReports;
                    }
                }
            }
        }
        private ICollection<PersonnelReport> _personnelReports;

        #endregion

        #region Association Fixup
    
        private void FixupAgency(Agency previousValue)
        {
            if (previousValue != null && previousValue.AppBudgetServices.Contains(this))
            {
                previousValue.AppBudgetServices.Remove(this);
            }
    
            if (Agency != null)
            {
                if (!Agency.AppBudgetServices.Contains(this))
                {
                    Agency.AppBudgetServices.Add(this);
                }
                if (AgencyId != Agency.Id)
                {
                    AgencyId = Agency.Id;
                }
            }
        }
    
        private void FixupService(Service previousValue)
        {
            if (previousValue != null && previousValue.AppBudgetServices.Contains(this))
            {
                previousValue.AppBudgetServices.Remove(this);
            }
    
            if (Service != null)
            {
                if (!Service.AppBudgetServices.Contains(this))
                {
                    Service.AppBudgetServices.Add(this);
                }
                if (ServiceId != Service.Id)
                {
                    ServiceId = Service.Id;
                }
            }
        }
    
        private void FixupAppBudget(AppBudget previousValue)
        {
            if (previousValue != null && previousValue.AppBudgetServices.Contains(this))
            {
                previousValue.AppBudgetServices.Remove(this);
            }
    
            if (AppBudget != null)
            {
                if (!AppBudget.AppBudgetServices.Contains(this))
                {
                    AppBudget.AppBudgetServices.Add(this);
                }
                if (AppBudgetId != AppBudget.Id)
                {
                    AppBudgetId = AppBudget.Id;
                }
            }
        }
    
        private void FixupSubReports(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SubReport item in e.NewItems)
                {
                    item.AppBudgetService = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SubReport item in e.OldItems)
                {
                    if (ReferenceEquals(item.AppBudgetService, this))
                    {
                        item.AppBudgetService = null;
                    }
                }
            }
        }
    
        private void FixupPersonnelReports(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PersonnelReport item in e.NewItems)
                {
                    item.AppBudgetService = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PersonnelReport item in e.OldItems)
                {
                    if (ReferenceEquals(item.AppBudgetService, this))
                    {
                        item.AppBudgetService = null;
                    }
                }
            }
        }

        #endregion

    }
}
