//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class AppExchangeRate
    {
        #region Primitive Properties
    
        public virtual int AppId
        {
            get { return _appId; }
            set
            {
                if (_appId != value)
                {
                    if (App != null && App.Id != value)
                    {
                        App = null;
                    }
                    _appId = value;
                }
            }
        }
        private int _appId;
    
        public virtual string CurId
        {
            get { return _curId; }
            set
            {
                if (_curId != value)
                {
                    if (Currency != null && Currency.Id != value)
                    {
                        Currency = null;
                    }
                    _curId = value;
                }
            }
        }
        private string _curId;
    
        public virtual decimal Value
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    		
    	public virtual Currency Currency
        {
            get { return _currency; }
            set
            {
                if (!ReferenceEquals(_currency, value))
                {
                    var previousValue = _currency;
                    _currency = value;
                    FixupCurrency(previousValue);
                }
            }
        }
        private Currency _currency;
    
    	
    	public virtual App App
        {
            get { return _app; }
            set
            {
                if (!ReferenceEquals(_app, value))
                {
                    var previousValue = _app;
                    _app = value;
                    FixupApp(previousValue);
                }
            }
        }
        private App _app;

        #endregion

        #region Association Fixup
    
        private void FixupCurrency(Currency previousValue)
        {
            if (previousValue != null && previousValue.AppExchangeRates.Contains(this))
            {
                previousValue.AppExchangeRates.Remove(this);
            }
    
            if (Currency != null)
            {
                if (!Currency.AppExchangeRates.Contains(this))
                {
                    Currency.AppExchangeRates.Add(this);
                }
                if (CurId != Currency.Id)
                {
                    CurId = Currency.Id;
                }
            }
        }
    
        private void FixupApp(App previousValue)
        {
            if (previousValue != null && previousValue.AppExchangeRates.Contains(this))
            {
                previousValue.AppExchangeRates.Remove(this);
            }
    
            if (App != null)
            {
                if (!App.AppExchangeRates.Contains(this))
                {
                    App.AppExchangeRates.Add(this);
                }
                if (AppId != App.Id)
                {
                    AppId = App.Id;
                }
            }
        }

        #endregion

    }
}
