//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class CfsAmount
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int Year
        {
            get;
            set;
        }
    
        public virtual string CurrencyId
        {
            get { return _currencyId; }
            set
            {
                if (_currencyId != value)
                {
                    if (Currency != null && Currency.Id != value)
                    {
                        Currency = null;
                    }
                    _currencyId = value;
                }
            }
        }
        private string _currencyId;
    
        public virtual int Level
        {
            get;
            set;
        }
    
        public virtual decimal Amount
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	
    	public virtual Currency Currency
        {
            get { return _currency; }
            set
            {
                if (!ReferenceEquals(_currency, value))
                {
                    var previousValue = _currency;
                    _currency = value;
                    FixupCurrency(previousValue);
                }
            }
        }
        private Currency _currency;
    
        public virtual ICollection<Country> Countries
        {
            get
            {
                if (_countries == null)
                {
                    var newCollection = new FixupCollection<Country>();
                    newCollection.CollectionChanged += FixupCountries;
                    _countries = newCollection;
                }
                return _countries;
            }
            set
            {
                if (!ReferenceEquals(_countries, value))
                {
                    var previousValue = _countries as FixupCollection<Country>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCountries;
                    }
                    _countries = value;
                    var newValue = value as FixupCollection<Country>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCountries;
                    }
                }
            }
        }
        private ICollection<Country> _countries;

        #endregion

        #region Association Fixup
    
        private void FixupCurrency(Currency previousValue)
        {
            if (previousValue != null && previousValue.CfsAmounts.Contains(this))
            {
                previousValue.CfsAmounts.Remove(this);
            }
    
            if (Currency != null)
            {
                if (!Currency.CfsAmounts.Contains(this))
                {
                    Currency.CfsAmounts.Add(this);
                }
                if (CurrencyId != Currency.Id)
                {
                    CurrencyId = Currency.Id;
                }
            }
        }
    
        private void FixupCountries(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Country item in e.NewItems)
                {
                    if (!item.CfsAmounts.Contains(this))
                    {
                        item.CfsAmounts.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Country item in e.OldItems)
                {
                    if (item.CfsAmounts.Contains(this))
                    {
                        item.CfsAmounts.Remove(this);
                    }
                }
            }
        }

        #endregion

    }
}
