//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class CfsEndDateReason
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual bool Show
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<CfsRow> CfsRows
        {
            get
            {
                if (_cfsRows == null)
                {
                    var newCollection = new FixupCollection<CfsRow>();
                    newCollection.CollectionChanged += FixupCfsRows;
                    _cfsRows = newCollection;
                }
                return _cfsRows;
            }
            set
            {
                if (!ReferenceEquals(_cfsRows, value))
                {
                    var previousValue = _cfsRows as FixupCollection<CfsRow>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCfsRows;
                    }
                    _cfsRows = value;
                    var newValue = value as FixupCollection<CfsRow>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCfsRows;
                    }
                }
            }
        }
        private ICollection<CfsRow> _cfsRows;

        #endregion

        #region Association Fixup
    
        private void FixupCfsRows(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CfsRow item in e.NewItems)
                {
                    item.CfsEndDateReason = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CfsRow item in e.OldItems)
                {
                    if (ReferenceEquals(item.CfsEndDateReason, this))
                    {
                        item.CfsEndDateReason = null;
                    }
                }
            }
        }

        #endregion

    }
}
