//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class ClientEventsCountReport
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int SubReportId
        {
            get { return _subReportId; }
            set
            {
                if (_subReportId != value)
                {
                    if (SubReport != null && SubReport.Id != value)
                    {
                        SubReport = null;
                    }
                    _subReportId = value;
                }
            }
        }
        private int _subReportId;
    
        public virtual System.DateTime EventDate
        {
            get;
            set;
        }
    
        public virtual int JNVCount
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TotalCount
        {
            get;
            set;
        }
    
        public virtual string Remarks
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	
    	public virtual SubReport SubReport
        {
            get { return _subReport; }
            set
            {
                if (!ReferenceEquals(_subReport, value))
                {
                    var previousValue = _subReport;
                    _subReport = value;
                    FixupSubReport(previousValue);
                }
            }
        }
        private SubReport _subReport;

        #endregion

        #region Association Fixup
    
        private void FixupSubReport(SubReport previousValue)
        {
            if (previousValue != null && previousValue.ClientEventsCountReports.Contains(this))
            {
                previousValue.ClientEventsCountReports.Remove(this);
            }
    
            if (SubReport != null)
            {
                if (!SubReport.ClientEventsCountReports.Contains(this))
                {
                    SubReport.ClientEventsCountReports.Add(this);
                }
                if (SubReportId != SubReport.Id)
                {
                    SubReportId = SubReport.Id;
                }
            }
        }

        #endregion

    }
}
