//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class Cri : CriBase
    {
        #region Navigation Properties
    
    	
    	public virtual Import Import
        {
            get { return _import; }
            set
            {
                if (!ReferenceEquals(_import, value))
                {
                    var previousValue = _import;
                    _import = value;
                    FixupImport(previousValue);
                }
            }
        }
        private Import _import;

        #endregion

        #region Association Fixup
    
        private void FixupImport(Import previousValue)
        {
            if (previousValue != null && previousValue.ImportClientReports.Contains(this))
            {
                previousValue.ImportClientReports.Remove(this);
            }
    
            if (Import != null)
            {
                if (!Import.ImportClientReports.Contains(this))
                {
                    Import.ImportClientReports.Add(this);
                }
                if (ImportId != Import.Id)
                {
                    ImportId = Import.Id;
                }
            }
        }

        #endregion

    }
}
