//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class DeletedClient
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> BirthDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LeaveDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> JoinDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime DeletedAt
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DeletedByUserId
        {
            get { return _deletedByUserId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_deletedByUserId != value)
                    {
                        if (User != null && User.Id != value)
                        {
                            User = null;
                        }
                        _deletedByUserId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _deletedByUserId;
    
        public virtual Nullable<int> DeleteRasonId
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    		
    	public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.DeletedClients.Contains(this))
            {
                previousValue.DeletedClients.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.DeletedClients.Contains(this))
                {
                    User.DeletedClients.Add(this);
                }
                if (DeletedByUserId != User.Id)
                {
                    DeletedByUserId = User.Id;
                }
            }
            else if (!_settingFK)
            {
                DeletedByUserId = null;
            }
        }

        #endregion

    }
}
