//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class EmergencyReport
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int SubReportId
        {
            get { return _subReportId; }
            set
            {
                if (_subReportId != value)
                {
                    if (SubReport != null && SubReport.Id != value)
                    {
                        SubReport = null;
                    }
                    _subReportId = value;
                }
            }
        }
        private int _subReportId;
    
        public virtual int ClientId
        {
            get { return _clientId; }
            set
            {
                if (_clientId != value)
                {
                    if (Client != null && Client.Id != value)
                    {
                        Client = null;
                    }
                    _clientId = value;
                }
            }
        }
        private int _clientId;
    
        public virtual int TypeId
        {
            get { return _typeId; }
            set
            {
                if (_typeId != value)
                {
                    if (EmergencyReportType != null && EmergencyReportType.Id != value)
                    {
                        EmergencyReportType = null;
                    }
                    _typeId = value;
                }
            }
        }
        private int _typeId;
    
        public virtual System.DateTime ReportDate
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Amount
        {
            get;
            set;
        }
    
        public virtual decimal Discretionary
        {
            get;
            set;
        }
    
        public virtual string Remarks
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Total
        {
            get;
            set;
        }
    
        public virtual string UniqueCircumstances
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	
    	public virtual SubReport SubReport
        {
            get { return _subReport; }
            set
            {
                if (!ReferenceEquals(_subReport, value))
                {
                    var previousValue = _subReport;
                    _subReport = value;
                    FixupSubReport(previousValue);
                }
            }
        }
        private SubReport _subReport;
    
    		
    	public virtual EmergencyReportType EmergencyReportType
        {
            get { return _emergencyReportType; }
            set
            {
                if (!ReferenceEquals(_emergencyReportType, value))
                {
                    var previousValue = _emergencyReportType;
                    _emergencyReportType = value;
                    FixupEmergencyReportType(previousValue);
                }
            }
        }
        private EmergencyReportType _emergencyReportType;
    
    	
    	public virtual Client Client
        {
            get { return _client; }
            set
            {
                if (!ReferenceEquals(_client, value))
                {
                    var previousValue = _client;
                    _client = value;
                    FixupClient(previousValue);
                }
            }
        }
        private Client _client;

        #endregion

        #region Association Fixup
    
        private void FixupSubReport(SubReport previousValue)
        {
            if (previousValue != null && previousValue.EmergencyReports.Contains(this))
            {
                previousValue.EmergencyReports.Remove(this);
            }
    
            if (SubReport != null)
            {
                if (!SubReport.EmergencyReports.Contains(this))
                {
                    SubReport.EmergencyReports.Add(this);
                }
                if (SubReportId != SubReport.Id)
                {
                    SubReportId = SubReport.Id;
                }
            }
        }
    
        private void FixupEmergencyReportType(EmergencyReportType previousValue)
        {
            if (previousValue != null && previousValue.EmergencyReports.Contains(this))
            {
                previousValue.EmergencyReports.Remove(this);
            }
    
            if (EmergencyReportType != null)
            {
                if (!EmergencyReportType.EmergencyReports.Contains(this))
                {
                    EmergencyReportType.EmergencyReports.Add(this);
                }
                if (TypeId != EmergencyReportType.Id)
                {
                    TypeId = EmergencyReportType.Id;
                }
            }
        }
    
        private void FixupClient(Client previousValue)
        {
            if (previousValue != null && previousValue.EmergencyReports.Contains(this))
            {
                previousValue.EmergencyReports.Remove(this);
            }
    
            if (Client != null)
            {
                if (!Client.EmergencyReports.Contains(this))
                {
                    Client.EmergencyReports.Add(this);
                }
                if (ClientId != Client.Id)
                {
                    ClientId = Client.Id;
                }
            }
        }

        #endregion

    }
}
