//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class HcCapsMonthlyTableRaw
    {
        #region Primitive Properties
    
        public virtual int ClientId
        {
            get;
            set;
        }
    
        public virtual int AgencyGroupId
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> StartDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> EndDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> JoinDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LeaveDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DeceasedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> HcCap
        {
            get;
            set;
        }
    
        public virtual decimal GovHcHours
        {
            get;
            set;
        }

        #endregion

    }
}
