//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class HcCap
    {
        #region Primitive Properties
    
        public virtual int ClientId
        {
            get;
            set;
        }
    
        public virtual System.DateTime ReportDate
        {
            get;
            set;
        }
    
        public virtual decimal Quantity
        {
            get;
            set;
        }
    
        public virtual decimal MonthlyCap
        {
            get;
            set;
        }
    
        public virtual decimal DailyCap
        {
            get;
            set;
        }

        #endregion

    }
}
