//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class HcStatus
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual int Cap
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<ClientHcStatus> ClientHcStatuses
        {
            get
            {
                if (_clientHcStatuses == null)
                {
                    var newCollection = new FixupCollection<ClientHcStatus>();
                    newCollection.CollectionChanged += FixupClientHcStatuses;
                    _clientHcStatuses = newCollection;
                }
                return _clientHcStatuses;
            }
            set
            {
                if (!ReferenceEquals(_clientHcStatuses, value))
                {
                    var previousValue = _clientHcStatuses as FixupCollection<ClientHcStatus>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupClientHcStatuses;
                    }
                    _clientHcStatuses = value;
                    var newValue = value as FixupCollection<ClientHcStatus>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupClientHcStatuses;
                    }
                }
            }
        }
        private ICollection<ClientHcStatus> _clientHcStatuses;

        #endregion

        #region Association Fixup
    
        private void FixupClientHcStatuses(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ClientHcStatus item in e.NewItems)
                {
                    item.HcStatus = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ClientHcStatus item in e.OldItems)
                {
                    if (ReferenceEquals(item.HcStatus, this))
                    {
                        item.HcStatus = null;
                    }
                }
            }
        }

        #endregion

    }
}
