//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class ImportClient
    {
        #region Primitive Properties
    
        public virtual System.Guid ImportId
        {
            get { return _importId; }
            set
            {
                if (_importId != value)
                {
                    if (Import != null && Import.Id != value)
                    {
                        Import = null;
                    }
                    _importId = value;
                }
            }
        }
        private System.Guid _importId;
    
        public virtual int RowIndex
        {
            get;
            set;
        }
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ClientId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MasterId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> AgencyId
        {
            get;
            set;
        }
    
        public virtual string NationalId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NationalIdTypeId
        {
            get;
            set;
        }
    
        public virtual string FirstName
        {
            get;
            set;
        }
    
        public virtual string MiddleName
        {
            get;
            set;
        }
    
        public virtual string LastName
        {
            get;
            set;
        }
    
        public virtual string Phone
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> BirthDate
        {
            get;
            set;
        }
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual string City
        {
            get;
            set;
        }
    
        public virtual Nullable<int> StateId
        {
            get;
            set;
        }
    
        public virtual string ZIP
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> JoinDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LeaveDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LeaveReasonId
        {
            get;
            set;
        }
    
        public virtual string LeaveRemarks
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DeceasedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ApprovalStatusId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FundStatusId
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IncomeCriteriaComplied
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IncomeVerificationRequired
        {
            get;
            set;
        }
    
        public virtual string NaziPersecutionDetails
        {
            get;
            set;
        }
    
        public virtual string Remarks
        {
            get;
            set;
        }
    
        public virtual string PobCity
        {
            get;
            set;
        }
    
        public virtual string PrevFirstName
        {
            get;
            set;
        }
    
        public virtual string PrevLastName
        {
            get;
            set;
        }
    
        public virtual string OtherFirstName
        {
            get;
            set;
        }
    
        public virtual string OtherLastName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> OtherDob
        {
            get;
            set;
        }
    
        public virtual string OtherId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OtherIdTypeId
        {
            get;
            set;
        }
    
        public virtual string OtherAddress
        {
            get;
            set;
        }
    
        public virtual string PreviousAddressInIsrael
        {
            get;
            set;
        }
    
        public virtual string CompensationProgramName
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsCeefRecipient
        {
            get;
            set;
        }
    
        public virtual string CeefId
        {
            get;
            set;
        }
    
        public virtual string AddCompName
        {
            get;
            set;
        }
    
        public virtual string AddCompId
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> ExceptionalHours
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> MatchFlag
        {
            get;
            set;
        }
    
        public virtual string New_Client
        {
            get;
            set;
        }
    
        public virtual int UpdatedById
        {
            get;
            set;
        }
    
        public virtual System.DateTime UpdatedAt
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedAt
        {
            get;
            set;
        }
    
        public virtual string InternalId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Gender
        {
            get;
            set;
        }
    
        public virtual Nullable<int> BirthCountryId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CountryId
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> HomecareWaitlist
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> OtherServicesWaitlist
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CommPrefsId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CareReceivedId
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> MAFDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> MAF105Date
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> UnableToSign
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> HAS2Date
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	
    	public virtual Import Import
        {
            get { return _import; }
            set
            {
                if (!ReferenceEquals(_import, value))
                {
                    var previousValue = _import;
                    _import = value;
                    FixupImport(previousValue);
                }
            }
        }
        private Import _import;

        #endregion

        #region Association Fixup
    
        private void FixupImport(Import previousValue)
        {
            if (previousValue != null && previousValue.ImportClients.Contains(this))
            {
                previousValue.ImportClients.Remove(this);
            }
    
            if (Import != null)
            {
                if (!Import.ImportClients.Contains(this))
                {
                    Import.ImportClients.Add(this);
                }
                if (ImportId != Import.Id)
                {
                    ImportId = Import.Id;
                }
            }
        }

        #endregion

    }
}
