//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class MainReportStatusAudit
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int MainReportId
        {
            get { return _mainReportId; }
            set
            {
                if (_mainReportId != value)
                {
                    if (MainReport != null && MainReport.Id != value)
                    {
                        MainReport = null;
                    }
                    _mainReportId = value;
                }
            }
        }
        private int _mainReportId;
    
        public virtual int OldStatusId
        {
            get;
            set;
        }
    
        public virtual int NewStatusId
        {
            get;
            set;
        }
    
        public virtual System.DateTime StatusChangeDate
        {
            get;
            set;
        }
    
        public virtual int UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (User != null && User.Id != value)
                    {
                        User = null;
                    }
                    _userId = value;
                }
            }
        }
        private int _userId;

        #endregion

        #region Navigation Properties
    
    	
    	public virtual MainReport MainReport
        {
            get { return _mainReport; }
            set
            {
                if (!ReferenceEquals(_mainReport, value))
                {
                    var previousValue = _mainReport;
                    _mainReport = value;
                    FixupMainReport(previousValue);
                }
            }
        }
        private MainReport _mainReport;
    
    	
    	public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion

        #region Association Fixup
    
        private void FixupMainReport(MainReport previousValue)
        {
            if (previousValue != null && previousValue.MainReportStatusAudits.Contains(this))
            {
                previousValue.MainReportStatusAudits.Remove(this);
            }
    
            if (MainReport != null)
            {
                if (!MainReport.MainReportStatusAudits.Contains(this))
                {
                    MainReport.MainReportStatusAudits.Add(this);
                }
                if (MainReportId != MainReport.Id)
                {
                    MainReportId = MainReport.Id;
                }
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.MainReportStatusAudits.Contains(this))
            {
                previousValue.MainReportStatusAudits.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.MainReportStatusAudits.Contains(this))
                {
                    User.MainReportStatusAudits.Add(this);
                }
                if (UserId != User.Id)
                {
                    UserId = User.Id;
                }
            }
        }

        #endregion

    }
}
