//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class MembershipUser
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (User != null && User.Id != value)
                    {
                        User = null;
                    }
                    _id = value;
                }
            }
        }
        private int _id;
    
        public virtual string LoweredUserName
        {
            get;
            set;
        }
    
        public virtual string LoweredEmail
        {
            get;
            set;
        }
    
        public virtual string Password
        {
            get;
            set;
        }
    
        public virtual int PasswordFormat
        {
            get;
            set;
        }
    
        public virtual string PasswordSalt
        {
            get;
            set;
        }
    
        public virtual string PasswordQuestion
        {
            get;
            set;
        }
    
        public virtual string PasswordAnswer
        {
            get;
            set;
        }
    
        public virtual bool IsApproved
        {
            get;
            set;
        }
    
        public virtual bool IsLockedOut
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreateDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastLoginDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastPasswordChangedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastLockoutDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FailedPasswordAttemptCount
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FailedPasswordAttemptWindowStart
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FailedPasswordAnswerAttemptCount
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FailedPasswordAnswerAttemptWindowStart
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ExpirationDate
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	
    	public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion

        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.MembershipUser, this))
            {
                previousValue.MembershipUser = null;
            }
    
            if (User != null)
            {
                User.MembershipUser = this;
                if (Id != User.Id)
                {
                    Id = User.Id;
                }
            }
        }

        #endregion

    }
}
