//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class MhmReport
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int SubReportId
        {
            get { return _subReportId; }
            set
            {
                if (_subReportId != value)
                {
                    if (SubReport != null && SubReport.Id != value)
                    {
                        SubReport = null;
                    }
                    _subReportId = value;
                }
            }
        }
        private int _subReportId;
    
        public virtual int ClientId
        {
            get { return _clientId; }
            set
            {
                if (_clientId != value)
                {
                    if (Client != null && Client.Id != value)
                    {
                        Client = null;
                    }
                    _clientId = value;
                }
            }
        }
        private int _clientId;
    
        public virtual int TypeId
        {
            get { return _typeId; }
            set
            {
                if (_typeId != value)
                {
                    if (MhmType != null && MhmType.Id != value)
                    {
                        MhmType = null;
                    }
                    _typeId = value;
                }
            }
        }
        private int _typeId;
    
        public virtual decimal Quantity
        {
            get;
            set;
        }
    
        public virtual decimal Amount
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	
    	public virtual SubReport SubReport
        {
            get { return _subReport; }
            set
            {
                if (!ReferenceEquals(_subReport, value))
                {
                    var previousValue = _subReport;
                    _subReport = value;
                    FixupSubReport(previousValue);
                }
            }
        }
        private SubReport _subReport;
    
    		
    	public virtual MhmType MhmType
        {
            get { return _mhmType; }
            set
            {
                if (!ReferenceEquals(_mhmType, value))
                {
                    var previousValue = _mhmType;
                    _mhmType = value;
                    FixupMhmType(previousValue);
                }
            }
        }
        private MhmType _mhmType;
    
    	
    	public virtual Client Client
        {
            get { return _client; }
            set
            {
                if (!ReferenceEquals(_client, value))
                {
                    var previousValue = _client;
                    _client = value;
                    FixupClient(previousValue);
                }
            }
        }
        private Client _client;

        #endregion

        #region Association Fixup
    
        private void FixupSubReport(SubReport previousValue)
        {
            if (previousValue != null && previousValue.MhmReports.Contains(this))
            {
                previousValue.MhmReports.Remove(this);
            }
    
            if (SubReport != null)
            {
                if (!SubReport.MhmReports.Contains(this))
                {
                    SubReport.MhmReports.Add(this);
                }
                if (SubReportId != SubReport.Id)
                {
                    SubReportId = SubReport.Id;
                }
            }
        }
    
        private void FixupMhmType(MhmType previousValue)
        {
            if (previousValue != null && previousValue.MhmReports.Contains(this))
            {
                previousValue.MhmReports.Remove(this);
            }
    
            if (MhmType != null)
            {
                if (!MhmType.MhmReports.Contains(this))
                {
                    MhmType.MhmReports.Add(this);
                }
                if (TypeId != MhmType.Id)
                {
                    TypeId = MhmType.Id;
                }
            }
        }
    
        private void FixupClient(Client previousValue)
        {
            if (previousValue != null && previousValue.MhmReports.Contains(this))
            {
                previousValue.MhmReports.Remove(this);
            }
    
            if (Client != null)
            {
                if (!Client.MhmReports.Contains(this))
                {
                    Client.MhmReports.Add(this);
                }
                if (ClientId != Client.Id)
                {
                    ClientId = Client.Id;
                }
            }
        }

        #endregion

    }
}
