//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class QRTZ_SIMPLE_TRIGGERS
    {
        #region Primitive Properties
    
        public virtual string SCHED_NAME
        {
            get { return _sCHED_NAME; }
            set
            {
                if (_sCHED_NAME != value)
                {
                    if (QRTZ_TRIGGERS != null && QRTZ_TRIGGERS.SCHED_NAME != value)
                    {
                        QRTZ_TRIGGERS = null;
                    }
                    _sCHED_NAME = value;
                }
            }
        }
        private string _sCHED_NAME;
    
        public virtual string TRIGGER_NAME
        {
            get { return _tRIGGER_NAME; }
            set
            {
                if (_tRIGGER_NAME != value)
                {
                    if (QRTZ_TRIGGERS != null && QRTZ_TRIGGERS.TRIGGER_NAME != value)
                    {
                        QRTZ_TRIGGERS = null;
                    }
                    _tRIGGER_NAME = value;
                }
            }
        }
        private string _tRIGGER_NAME;
    
        public virtual string TRIGGER_GROUP
        {
            get { return _tRIGGER_GROUP; }
            set
            {
                if (_tRIGGER_GROUP != value)
                {
                    if (QRTZ_TRIGGERS != null && QRTZ_TRIGGERS.TRIGGER_GROUP != value)
                    {
                        QRTZ_TRIGGERS = null;
                    }
                    _tRIGGER_GROUP = value;
                }
            }
        }
        private string _tRIGGER_GROUP;
    
        public virtual int REPEAT_COUNT
        {
            get;
            set;
        }
    
        public virtual long REPEAT_INTERVAL
        {
            get;
            set;
        }
    
        public virtual int TIMES_TRIGGERED
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    		
    	public virtual QRTZ_TRIGGERS QRTZ_TRIGGERS
        {
            get { return _qRTZ_TRIGGERS; }
            set
            {
                if (!ReferenceEquals(_qRTZ_TRIGGERS, value))
                {
                    var previousValue = _qRTZ_TRIGGERS;
                    _qRTZ_TRIGGERS = value;
                    FixupQRTZ_TRIGGERS(previousValue);
                }
            }
        }
        private QRTZ_TRIGGERS _qRTZ_TRIGGERS;

        #endregion

        #region Association Fixup
    
        private void FixupQRTZ_TRIGGERS(QRTZ_TRIGGERS previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.QRTZ_SIMPLE_TRIGGERS, this))
            {
                previousValue.QRTZ_SIMPLE_TRIGGERS = null;
            }
    
            if (QRTZ_TRIGGERS != null)
            {
                QRTZ_TRIGGERS.QRTZ_SIMPLE_TRIGGERS = this;
                if (SCHED_NAME != QRTZ_TRIGGERS.SCHED_NAME)
                {
                    SCHED_NAME = QRTZ_TRIGGERS.SCHED_NAME;
                }
                if (TRIGGER_NAME != QRTZ_TRIGGERS.TRIGGER_NAME)
                {
                    TRIGGER_NAME = QRTZ_TRIGGERS.TRIGGER_NAME;
                }
                if (TRIGGER_GROUP != QRTZ_TRIGGERS.TRIGGER_GROUP)
                {
                    TRIGGER_GROUP = QRTZ_TRIGGERS.TRIGGER_GROUP;
                }
            }
        }

        #endregion

    }
}
