//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class QRTZ_FIRED_TRIGGERS
    {
        #region Primitive Properties
    
        public virtual string SCHED_NAME
        {
            get;
            set;
        }
    
        public virtual string ENTRY_ID
        {
            get;
            set;
        }
    
        public virtual string TRIGGER_NAME
        {
            get;
            set;
        }
    
        public virtual string TRIGGER_GROUP
        {
            get;
            set;
        }
    
        public virtual string INSTANCE_NAME
        {
            get;
            set;
        }
    
        public virtual long FIRED_TIME
        {
            get;
            set;
        }
    
        public virtual long SCHED_TIME
        {
            get;
            set;
        }
    
        public virtual int PRIORITY
        {
            get;
            set;
        }
    
        public virtual string STATE
        {
            get;
            set;
        }
    
        public virtual string JOB_NAME
        {
            get;
            set;
        }
    
        public virtual string JOB_GROUP
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IS_NONCONCURRENT
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> REQUESTS_RECOVERY
        {
            get;
            set;
        }

        #endregion

    }
}
