//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class QRTZ_LOCKS
    {
        #region Primitive Properties
    
        public virtual string SCHED_NAME
        {
            get;
            set;
        }
    
        public virtual string LOCK_NAME
        {
            get;
            set;
        }

        #endregion

    }
}
