//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class Resource
    {
        #region Primitive Properties
    
        public virtual string Culture
        {
            get { return _culture; }
            set
            {
                if (_culture != value)
                {
                    if (Language != null && Language.Id != value)
                    {
                        Language = null;
                    }
                    _culture = value;
                }
            }
        }
        private string _culture;
    
        public virtual string Key
        {
            get;
            set;
        }
    
        public virtual string Value
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    		
    	public virtual Language Language
        {
            get { return _language; }
            set
            {
                if (!ReferenceEquals(_language, value))
                {
                    var previousValue = _language;
                    _language = value;
                    FixupLanguage(previousValue);
                }
            }
        }
        private Language _language;

        #endregion

        #region Association Fixup
    
        private void FixupLanguage(Language previousValue)
        {
            if (previousValue != null && previousValue.Resources.Contains(this))
            {
                previousValue.Resources.Remove(this);
            }
    
            if (Language != null)
            {
                if (!Language.Resources.Contains(this))
                {
                    Language.Resources.Add(this);
                }
                if (Culture != Language.Id)
                {
                    Culture = Language.Id;
                }
            }
        }

        #endregion

    }
}
