//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class SKMembersVisit
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int SKReportId
        {
            get { return _sKReportId; }
            set
            {
                if (_sKReportId != value)
                {
                    if (SoupKitchensReport != null && SoupKitchensReport.Id != value)
                    {
                        SoupKitchensReport = null;
                    }
                    _sKReportId = value;
                }
            }
        }
        private int _sKReportId;
    
        public virtual System.DateTime ReportDate
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    		
    	public virtual SoupKitchensReport SoupKitchensReport
        {
            get { return _soupKitchensReport; }
            set
            {
                if (!ReferenceEquals(_soupKitchensReport, value))
                {
                    var previousValue = _soupKitchensReport;
                    _soupKitchensReport = value;
                    FixupSoupKitchensReport(previousValue);
                }
            }
        }
        private SoupKitchensReport _soupKitchensReport;

        #endregion

        #region Association Fixup
    
        private void FixupSoupKitchensReport(SoupKitchensReport previousValue)
        {
            if (previousValue != null && previousValue.SKMembersVisits.Contains(this))
            {
                previousValue.SKMembersVisits.Remove(this);
            }
    
            if (SoupKitchensReport != null)
            {
                if (!SoupKitchensReport.SKMembersVisits.Contains(this))
                {
                    SoupKitchensReport.SKMembersVisits.Add(this);
                }
                if (SKReportId != SoupKitchensReport.Id)
                {
                    SKReportId = SoupKitchensReport.Id;
                }
            }
        }

        #endregion

    }
}
