//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class SupportiveCommunitiesReport
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int SubReportId
        {
            get { return _subReportId; }
            set
            {
                if (_subReportId != value)
                {
                    if (SubReport != null && SubReport.Id != value)
                    {
                        SubReport = null;
                    }
                    _subReportId = value;
                }
            }
        }
        private int _subReportId;
    
        public virtual int ClientId
        {
            get { return _clientId; }
            set
            {
                if (_clientId != value)
                {
                    if (Client != null && Client.Id != value)
                    {
                        Client = null;
                    }
                    _clientId = value;
                }
            }
        }
        private int _clientId;
    
        public virtual Nullable<decimal> HoursHoldCost
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Amount
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MonthsCount
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	
    	public virtual Client Client
        {
            get { return _client; }
            set
            {
                if (!ReferenceEquals(_client, value))
                {
                    var previousValue = _client;
                    _client = value;
                    FixupClient(previousValue);
                }
            }
        }
        private Client _client;
    
    	
    	public virtual SubReport SubReport
        {
            get { return _subReport; }
            set
            {
                if (!ReferenceEquals(_subReport, value))
                {
                    var previousValue = _subReport;
                    _subReport = value;
                    FixupSubReport(previousValue);
                }
            }
        }
        private SubReport _subReport;

        #endregion

        #region Association Fixup
    
        private void FixupClient(Client previousValue)
        {
            if (previousValue != null && previousValue.SupportiveCommunitiesReports.Contains(this))
            {
                previousValue.SupportiveCommunitiesReports.Remove(this);
            }
    
            if (Client != null)
            {
                if (!Client.SupportiveCommunitiesReports.Contains(this))
                {
                    Client.SupportiveCommunitiesReports.Add(this);
                }
                if (ClientId != Client.Id)
                {
                    ClientId = Client.Id;
                }
            }
        }
    
        private void FixupSubReport(SubReport previousValue)
        {
            if (previousValue != null && previousValue.SupportiveCommunitiesReports.Contains(this))
            {
                previousValue.SupportiveCommunitiesReports.Remove(this);
            }
    
            if (SubReport != null)
            {
                if (!SubReport.SupportiveCommunitiesReports.Contains(this))
                {
                    SubReport.SupportiveCommunitiesReports.Add(this);
                }
                if (SubReportId != SubReport.Id)
                {
                    SubReportId = SubReport.Id;
                }
            }
        }

        #endregion

    }
}
