//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class viewGgQuarterlyHcFl
    {
        #region Primitive Properties
    
        public virtual int ClientId
        {
            get;
            set;
        }
    
        public virtual int RepYear
        {
            get;
            set;
        }
    
        public virtual int RepQuarter
        {
            get;
            set;
        }
    
        public virtual int FundId
        {
            get;
            set;
        }
    
        public virtual int AgencyGroupId
        {
            get;
            set;
        }
    
        public virtual int RelatedLevelId
        {
            get;
            set;
        }

        #endregion

    }
}
