//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class viewClientReportsEst
    {
        #region Primitive Properties
    
        public virtual int SubReportId
        {
            get;
            set;
        }
    
        public virtual int ClientId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TypeId
        {
            get;
            set;
        }
    
        public virtual string TypeName
        {
            get;
            set;
        }
    
        public virtual string PurposeOfGrant
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Quantity
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Rate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ReportDate
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Amount
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Discretionary
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> TotalAmount
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> EstAmount
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> EstReportDate
        {
            get;
            set;
        }

        #endregion

    }
}
