//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class viewClientDetail
    {
        #region Primitive Properties
    
        public virtual string InternalAgencyID
        {
            get;
            set;
        }
    
        public virtual int ORGID
        {
            get;
            set;
        }
    
        public virtual string Agency
        {
            get;
            set;
        }
    
        public virtual string FirstName
        {
            get;
            set;
        }
    
        public virtual string LastName
        {
            get;
            set;
        }
    
        public virtual string MiddleName
        {
            get;
            set;
        }
    
        public virtual string OtherFirstName
        {
            get;
            set;
        }
    
        public virtual string OtherLastName
        {
            get;
            set;
        }
    
        public virtual string PreviousFirstName
        {
            get;
            set;
        }
    
        public virtual string PreviousLastName
        {
            get;
            set;
        }
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual string City
        {
            get;
            set;
        }
    
        public virtual string ZIP
        {
            get;
            set;
        }
    
        public virtual string State
        {
            get;
            set;
        }
    
        public virtual string CountryName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> BirthDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Otherdateofbirth
        {
            get;
            set;
        }
    
        public virtual string BirthCity
        {
            get;
            set;
        }
    
        public virtual string BirthCountry
        {
            get;
            set;
        }
    
        public virtual string IDType
        {
            get;
            set;
        }
    
        public virtual string OtherIDcard
        {
            get;
            set;
        }
    
        public virtual string OtherIDtype
        {
            get;
            set;
        }
    
        public virtual string GovernmentIssuedID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DeceasedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LeaveDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime JoinDate
        {
            get;
            set;
        }
    
        public virtual string LeaveReason
        {
            get;
            set;
        }
    
        public virtual string Remarks
        {
            get;
            set;
        }
    
        public virtual bool IncomeCriteriaComplied
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Gender
        {
            get;
            set;
        }
    
        public virtual int CCID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MasterId
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreateDate
        {
            get;
            set;
        }
    
        public virtual string FunctionalityLevelName
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> GrandfatheredHours
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> GFStartDate
        {
            get;
            set;
        }
    
        public virtual string GFType
        {
            get;
            set;
        }
    
        public virtual string ApprovalStatus
        {
            get;
            set;
        }
    
        public virtual string NaziPersecutionDetails
        {
            get;
            set;
        }
    
        public virtual string CompensationProgram
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> HomecareEligibilityStartDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> HomecareEligibilityEndDate
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> GovtHChours
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> GovtHChoursStartDate
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> DiagnosticScore
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> HighestStartDateofDiagnosticScore
        {
            get;
            set;
        }
    
        public virtual string Otheraddress
        {
            get;
            set;
        }
    
        public virtual string PreviousaddressinIsrael
        {
            get;
            set;
        }
    
        public virtual string Phone
        {
            get;
            set;
        }
    
        public virtual bool AustrianEligible
        {
            get;
            set;
        }
    
        public virtual bool RomanianEligible
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> GGReportedOnly
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UnmetNeedsStartDate
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> UnmetNeedsValue
        {
            get;
            set;
        }
    
        public virtual string HomecareApprovalStatusName
        {
            get;
            set;
        }
    
        public virtual bool IsCeefRecipient
        {
            get;
            set;
        }
    
        public virtual string CeefId
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> HcHours
        {
            get;
            set;
        }
    
        public virtual int AgencyId
        {
            get;
            set;
        }
    
        public virtual bool SC_Client
        {
            get;
            set;
        }
    
        public virtual bool DCC_Client
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GGReportedCount
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedAt
        {
            get;
            set;
        }
    
        public virtual int AgencyGroupId
        {
            get;
            set;
        }
    
        public virtual int ApprovalStatusId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> RegionId
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> AppearedAtLeastOnce
        {
            get;
            set;
        }
    
        public virtual bool HomecareWaitlist
        {
            get;
            set;
        }
    
        public virtual bool OtherServicesWaitlist
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> MAFDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> MAF105Date
        {
            get;
            set;
        }
    
        public virtual string CommPrefs
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CommPrefsId
        {
            get;
            set;
        }
    
        public virtual string CareReceivedVia
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CareReceivedId
        {
            get;
            set;
        }
    
        public virtual bool UnableToSign
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Has2Date
        {
            get;
            set;
        }

        #endregion

    }
}
