//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class viewScRepSource
    {
        #region Primitive Properties
    
        public virtual int subreportid
        {
            get;
            set;
        }
    
        public virtual int clientid
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> HoursHoldCost
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MonthsCount
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Amount
        {
            get;
            set;
        }
    
        public virtual int MrStatusId
        {
            get;
            set;
        }

        #endregion

    }
}
