//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class viewHcPlu
    {
        #region Primitive Properties
    
        public virtual int ClientId
        {
            get;
            set;
        }
    
        public virtual System.DateTime ReportDate
        {
            get;
            set;
        }
    
        public virtual int MrId
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> C
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> WC
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> q
        {
            get;
            set;
        }

        #endregion

    }
}
