//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class viewFinancialReportApprovalStatusReport
    {
        #region Primitive Properties
    
        public virtual int MainReportId
        {
            get;
            set;
        }
    
        public virtual int RegionId
        {
            get;
            set;
        }
    
        public virtual int CountryId
        {
            get;
            set;
        }
    
        public virtual int AgencyGroupId
        {
            get;
            set;
        }
    
        public virtual string AppName
        {
            get;
            set;
        }
    
        public virtual System.DateTime Start
        {
            get;
            set;
        }
    
        public virtual System.DateTime End
        {
            get;
            set;
        }
    
        public virtual string AgencyName
        {
            get;
            set;
        }
    
        public virtual System.DateTime StatusChangeDate
        {
            get;
            set;
        }
    
        public virtual int NewStatusId
        {
            get;
            set;
        }
    
        public virtual int OldStatusId
        {
            get;
            set;
        }

        #endregion

    }
}
