//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CC.Data
{
    public partial class viewFunctionalityScoreChangeReport
    {
        #region Primitive Properties
    
        public virtual int ClientId
        {
            get;
            set;
        }
    
        public virtual int RegionId
        {
            get;
            set;
        }
    
        public virtual int CountryId
        {
            get;
            set;
        }
    
        public virtual int AgencyGroupId
        {
            get;
            set;
        }
    
        public virtual string AgencyName
        {
            get;
            set;
        }
    
        public virtual decimal DiagnosticScore
        {
            get;
            set;
        }
    
        public virtual System.DateTime UpdatedAt
        {
            get;
            set;
        }
    
        public virtual System.DateTime StartDate
        {
            get;
            set;
        }

        #endregion

    }
}
