insert into dbo.MedicalEquipmentTypes(name) values('Eye glasses ')
insert into dbo.MedicalEquipmentTypes(name) values('Hearing aides ')
insert into dbo.MedicalEquipmentTypes(name) values('Wheel chairs ')
insert into dbo.MedicalEquipmentTypes(name) values('Prosthetic devices ')
insert into dbo.MedicalEquipmentTypes(name) values('Special beds ')
insert into dbo.MedicalEquipmentTypes(name) values('Hospital equipment needed at home-(oxygen masks) ')
insert into dbo.MedicalEquipmentTypes(name) values('Personal emergency response system/installation of such equipment (not for Blue Card clients) ')
insert into dbo.MedicalEquipmentTypes(name) values('Supportive footwear ')
insert into dbo.MedicalEquipmentTypes(name) values('Stockings ')
insert into dbo.MedicalEquipmentTypes(name) values('Walkers/canes ')
insert into dbo.MedicalEquipmentTypes(name) values('Oxygen masks ')
insert into dbo.MedicalEquipmentTypes(name) values('Orthotics ')
insert into dbo.MedicalEquipmentTypes(name) values('Bed pans ')
insert into dbo.MedicalEquipmentTypes(name) values('Special chairs')