//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CC.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;!--Claims Conference Home Care Services			
        ///2016 Diagnostic Assessment Form			
        ///			
        ///Agency Name  			
        ///Client’s Full Name			
        ///Date of Assessment		Form #	
        ///			
        ///The following are 14 diagnostic tables that assess each individual client’s functionality status.  In each table, please fill in the corresponding number for the one answer that best describes the client’s functionality status, based on the descriptions below each function.--&gt;
        ///&lt;root&gt;
        ///	&lt;q id=&quot;1&quot; text=&quot;Mobil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DAF_v1 {
            get {
                return ResourceManager.GetString("DAF_v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ServiceTypes&gt;
        ///  &lt;Service&gt;
        ///    &lt;Type&gt;Emergency Assistance&lt;/Type&gt;
        ///    &lt;Name&gt;Housing &amp;amp; Related Costs&lt;/Name&gt;
        ///    &lt;ReportingType&gt;1&lt;/ReportingType&gt;
        ///  &lt;/Service&gt;
        ///  &lt;Service&gt;
        ///    &lt;Type&gt;Emergency Assistance&lt;/Type&gt;
        ///    &lt;Name&gt;Dental&lt;/Name&gt;
        ///    &lt;ReportingType&gt;1&lt;/ReportingType&gt;
        ///  &lt;/Service&gt;
        ///  &lt;Service&gt;
        ///    &lt;Type&gt;Emergency Assistance&lt;/Type&gt;
        ///    &lt;Name&gt;Food&lt;/Name&gt;
        ///    &lt;ReportingType&gt;1&lt;/ReportingType&gt;
        ///  &lt;/Service&gt;
        ///  &lt;Service&gt;
        ///    &lt;Type&gt;Emergency Assistance&lt;/Type&gt;
        ///    &lt;Name&gt;Medical&lt;/Name&gt;
        ///    &lt;Reporti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
    }
}
