--migrate pobcountry to birthcountryid
--run before deployment of the birthcountryid

if object_id('dbo.birthcountries') is null
begin
	create table dbo.BirthCountries(Id int not null identity,
		Name nvarchar(50))
	
	insert into dbo.BirthCountries(name)
	select 'Birth Country Required'
	union select 'Albania'
	union select 'Algeria'
	union select 'Armenia'
	union select 'Andorra'
	union select 'Austria'
	union select 'Azerbaijan'
	union select 'Belarus'
	union select 'Belgium'
	union select 'Bosnia and Herzegovina'
	union select 'Bulgaria'
	union select 'Croatia'
	union select 'Czech Republic'
	union select 'Czechoslovakia'
	union select 'Denmark'
	union select 'Egypt'
	union select 'Estonia'
	union select 'Finland'
	union select 'France'
	union select 'FSU'
	union select 'FYROM'
	union select 'Georgia'
	union select 'Germany'
	union select 'Greece'
	union select 'Hungary'
	union select 'Italy'
	union select 'Kazakhstan'
	union select 'Kosovo'
	union select 'Kyrgyzstan'
	union select 'Latvia'
	union select 'Libya'
	union select 'Lithuania'
	union select 'Luxembourg'
	union select 'Moldova'
	union select 'Monaco'
	union select 'Montenegro'
	union select 'Morocco'
	union select 'Netherlands'
	union select 'Norway'
	union select 'Other'
	union select 'Poland'
	union select 'Romania'
	union select 'Russia'
	union select 'San Marino'
	union select 'Serbia'
	union select 'Slovakia'
	union select 'Slovenia'
	union select 'Spain'
	union select 'Switzerland'
	union select 'Tajikistan'
	union select 'Tunisia'
	union select 'Turkey'
	union select 'Turkmenistan'
	union select 'Ukraine'
	union select 'United Kingdom'
	union select 'Uzbekistan'
	union select 'Yugoslavia'

	declare @t2 table(a nvarchar(400), b nvarchar(400));
	insert into @t2
		select'16 oct 19884','Other'
	union select '', 'Other'
	union select '1', 'Other'
	union select'2107','Other'
	union select'Abchasia','Georgia'
	union select'Adygeya Rep SSSR','Russia'
	union select'Alemania','Germany'
	union select'ALGERIE','Algeria'
	union select'Algérie','Algeria'
	union select'ALLEMAGNE','Germany'
	union select'AMERICA UNKNOWN','Other'
	union select'ARGENTINA','Other'
	union select'Armenia','Armenia'
	union select'Astrohanskaya','Russia'
	union select'AUSTRALIA','Other'
	union select'AUSTRO-HUNGARY','Hungary'
	union select'AUSTRO-UNGAREN','Hungary'
	union select'Autriche','Austria'
	union select'Azerbaidschan','Azerbaijan'
	union select'AZERBAIJAN','Azerbaijan'
	union select'Azerbajdzan','Azerbaijan'
	union select'B','Other'
	union select'B&H','Bosnia and Herzegovina'
	union select'Babrusk','Belarus'
	union select'Bashkiria','Russia'
	union select'Bashkirskaya ASSR','Russia'
	union select'Bela Rus','Belarus'
	union select'Belanus (Russia)','Belarus'
	union select'BELARUS','Belarus'
	union select'Belarus USSR','Belarus'
	union select'Belarus.','Belarus'
	union select'Belaruss','Belarus'
	union select'Belarussia','Belarus'
	union select'Bearus','Belarus'
	union select'Belarussia USSR','Belarus'
	union select'Belaurussia','Belarus'
	union select'Belgica','Belgium'
	union select'BELGIQUE','Belgium'
	union select'Belguim','Belgium'
	union select'Belgie','Belgium'
	union select'BELIZE','Other'
	union select'Bellarus','Belarus'
	union select'Bellaruss','Belarus'
	union select'Bellorussia','Belarus'
	union select'Belorrusia','Belarus'
	union select'Belorrussia','Belarus'
	union select'Belorus','Belarus'
	union select'Beloruss','Belarus'
	union select'Belorussia','Belarus'
	union select'Berehove','Ukraine'
	union select'Berorussia','Belarus'
	union select'Belarous','Belarus'
	union select'Bershad','Ukraine'
	union select'Bessarabia','Moldova'
	union select'Blearus (Russia)','Belarus'
	union select'BLR','Belarus'
	union select'Bolgaria','Bulgaria'
	union select'BOLIVIA','Other'
	union select'BOSNIA','Bosnia and Herzegovina'
	union select'Bosnia/Herzegovina','Bosnia and Herzegovina'
	union select'Bresil','Other'
	union select'Breslau','Poland'
	union select'BRUSSELS','Belgium'
	union select'BSSR','Belarus'
	union select'BUCURESTI','Romania'
	union select'Budapest','Hungary'
	union select'Budapest, Hungary','Hungary'
	union select'Bukovina/Ukraine','Ukraine'
	union select'Bulgary','Bulgaria'
	union select'Byelorussia','Belarus'
	union select'C','Other'
	union select'Caecholsovakia','Czech Republic'
	union select'CANADA','Other'
	union select'Caucasus, FSU','FSU'
	union select'CEHOSLOVACIA','Czech Republic'
	union select'Checheslovakia','Czech Republic'
	union select'Chechoslavakia','Czech Republic'
	union select'Chechoslovakia','Czech Republic'
	union select'Checkoslavakia','Czech Republic'
	union select'Checkoslovakia','Czech Republic'
	union select'Checoslovakia','Czech Republic'
	union select'Checoslovaquia','Czech Republic'
	union select'Chekoslovakia','Czech Republic'
	union select'Czechlovakia','Czech Republic'
	union select'Chezanow','Poland'
	union select'CHILE','Other'
	union select'China','Other'
	union select'CHUST','Ukraine'
	union select'Colombia','Other'
	union select'CONGO','Other'
	union select'Croatia/Yugoslavia','Croatia'
	union select'Csorna','Hungary'
	union select'csr','Czech Republic'
	union select'Cuba','Other'
	union select'Cxechoslovaki','Czech Republic'
	union select'cz','Czech Republic'
	union select'Czch','Czech Republic'
	union select'CZEC','Czech Republic'
	union select'Czech','Czech Republic'
	union select'Czech/Hungary','Hungary'
	union select'Czechaslovakia','Czech Republic'
	union select'Czechaslovkia','Czech Republic'
	union select'Czecheslovakia','Czech Republic'
	union select'Czechia','Czech Republic'
	union select'Czechkoslovakia','Czech Republic'
	union select'Czechleslovkia','Czech Republic'
	union select'Czecholosavakia','Czech Republic'
	union select'Czecholosvakia','Czech Republic'
	union select'Czecholovakia','Czech Republic'
	union select'Czechos.','Czech Republic'
	union select'Czechoslakia','Czech Republic'
	union select'Czechoslavaki','Czech Republic'
	union select'Czechoslavakia','Czech Republic'
	union select'Czechoslavokia','Czech Republic'
	union select'Czechoslovakia','Czech Republic'
	union select'Czechoslovakia/ Hungary','Hungary'
	union select'Czechoslovakia/Hungary','Hungary'
	union select'Czechoslovakiya','Czech Republic'
	union select'Czechoslovalia','Czech Republic'
	union select'Czechoslvakia','Czech Republic'
	union select'Czechosolovakia','Czech Republic'
	union select'Czechosolvakia','Czech Republic'
	union select'Czechslovakia','Czech Republic'
	union select'Czechsovakia','Czech Republic'
	union select'Czeck','Czech Republic'
	union select'Czeckoslavakia','Czech Republic'
	union select'Czeckoslavia','Czech Republic'
	union select'Czeckoslovakia','Czech Republic'
	union select'Czeh','Czech Republic'
	union select'Dagestan','Russia'
	union select'Denemarken','Denmark'
	union select'Deutschland','Germany'
	union select'Duitsland','Germany'
	union select'East Germany','Germany'
	union select'Eastern Poland','Poland'
	union select'EGYPT','Egypt'
	union select'England','United Kingdom'
	union select'ESPAGNE','Spain'
	union select'Europe','Other'
	union select'former Czechoslovakia','Czech Republic'
	union select'Former USSR','FSU'
	union select'Fra','France'
	union select'France/ Belgium','France'
	union select'Frankreich','France'
	union select'Free city of Dansig','Poland'
	union select'Frnace','France'
	union select'FSU','FSU'
	union select'Galizia','Poland'
	union select'Galizien','Poland'
	union select'GEORGIA','Georgia'
	union select'Georgien','Georgia'
	union select'Ger','Germany'
	union select'Geremany','Germany'
	union select'German','Germany'
	union select'Germany/Poland','Poland'
	union select'Grabana','Other'
	union select'GREAT BRITAIN','United Kingdom'
	union select'Gzechoslovakia','Czech Republic'
	union select'h','Other'
	union select'Holland','Netherlands'
	union select'Hongrie','Hungary'
	union select'Humgary','Hungary'
	union select'Hungray','Hungary'
	union select'hung','Hungary'
	union select'Hungaria','Hungary'
	union select'Hungarian','Hungary'
	union select'Hungary/Czech','Hungary'
	union select'Hungary/Romania','Hungary'
	union select'Hungary-then it became Romania','Romania'
	union select'Hungry','Hungary'
	union select'INDONESIA','Other'
	union select'ISRAEL','Other'
	union select'Italie','Italy'
	union select'Italien','Italy'
	union select'Karsava','Other'
	union select'Kasachstan','Kazakhstan'
	union select'Kasho','Other'
	union select'Kazachstan','Kazakhstan'
	union select'Kazahstan','Kazakhstan'
	union select'KAZAKHSTAN','Kazakhstan'
	union select'Kazansky Region, Russia','Russia'
	union select'Khazakistan','Kazakhstan'
	union select'Kiev','Ukraine'
	union select'Kirgizia','Kyrgyzstan'
	union select'Kischinjow','Moldova'
	union select'Moldavien(Besarabien)','Moldova'
	union select'KRG','Other'
	union select'Kroatia','Croatia'
	union select'Latvia (USSR)','Latvia'
	union select'Latvien','Latvia'
	union select'Latwien','Latvia'
	union select'LEBANON','Other'
	union select'Leningrad','Russia'
	union select'Letland','Latvia'
	union select'Lettland','Latvia'
	union select'Libia','Libya'
	union select'LIBYE','Libya'
	union select'Liminova','Other'
	union select'Litauen','Lithuania'
	union select'Lithewania','Lithuania'
	union select'Lithuanian SSR','Lithuania'
	union select'LITUANIE','Lithuania'
	union select'Lituuania','Lithuania'
	union select'Ltuvenia','Lithuania'
	union select'Lutauen','Lithuania'
	union select'LVA','Other'
	union select'LYBIA','Libya'
	union select'Macedonia','FYROM'
	union select'Madagascar','Other'
	union select'Makova','Other'
	union select'MALAYSIA','Other'
	union select'Maroc','Morocco'
	union select'MAROCCO','Morocco'
	union select'MDA','Other'
	union select'Moldau','Moldova'
	union select'Moldava','Moldova'
	union select'Moldavia','Moldova'
	union select'Moldavia/Romania','Moldova'
	union select'Moldavien','Moldova'
	union select'Moldawien','Moldova'
	union select'Moldova, USSR','Moldova'
	union select'Moldovia','Moldova'
	union select'Moldovoa','Moldova'
	union select'Moldowa','Moldova'
	union select'Moldowien','Moldova'
	union select'Molodavien','Moldova'
	union select'Molova','Moldova'
	union select'Mongolia','Other'
	union select'Monoco','Monaco'
	union select'Monte Carlo','Monaco'
	union select'Moracco','Morocco'
	union select'Morrocco','Morocco'
	union select'Moscow','Russia'
	union select'munkacevo','Ukraine'
	union select'Munkatabor','Other'
	union select'Netherland','Netherlands'
	union select'New York','Other'
	union select'NIRBATER','Hungary'
	union select'Nordossetien','Russia'
	union select'Odessa','Ukraine'
	union select'Oostenrijk','Austria'
	union select'Ostroff','Other'
	union select'Paks','Hungary'
	union select'Palestine','Other'
	union select'Peru','Other'
	union select'Pland','Poland'
	union select'po','Poland'
	union select'POL','Poland'
	union select'Polan','Poland'
	union select'Poland (now Ukraine)','Ukraine'
	union select'Poland Lizensk','Poland'
	union select'Polen','Poland'
	union select'Polen jetzt Weissrussland','Belarus'
	union select'POLGNE','Poland'
	union select'Polland','Poland'
	union select'POLOGNA','Poland'
	union select'Pologne','Poland'
	union select'Polonia','Poland'
	union select'Razon','Other'
	union select'REP MOLDOVA','Moldova'
	union select'REP. MOLDOVA','Moldova'
	union select'Republika Hrvatska','Croatia'
	union select'Riga','Latvia'
	union select'RO9MANIA','Romania'
	union select'Roemenie','Romania'
	union select'Roemenië','Romania'
	union select'Romaina','Romania'
	union select'ROMANA','Romania'
	union select'Romani','Romania'
	union select'Romania changed to Ukraine','Ukraine'
	union select'Romania/Moldova','Moldova'
	union select'Romania (Moldovia)','Moldova'
	union select'Romanis','Romania'
	union select'Romaniya','Romania'
	union select'Roumania','Romania'
	union select'Roumanie','Romania'
	union select'Rum aenien','Romania'
	union select'Rumaenien','Romania'
	union select'Rumania','Romania'
	union select'RumAnien','Romania'
	union select'Rumany','Romania'
	union select'Rumenium','Romania'
	union select'RUS','Russia'
	union select'Rusia','Russia'
	union select'Rusland','Russia'
	union select'Russa','Russia'
	union select'Russia (USSR)','Russia'
	union select'Russia / Belarus','Russia'
	union select'Russia USSR','Russia'
	union select'Russian','Russia'
	union select'Russian Empire','Russia'
	union select'RUSSIAN FEDERATION','Russia'
	union select'Russl.','Russia'
	union select'Russland','Russia'
	union select'Russland  UdSSR','Russia'
	union select'Sat Mar','Romania'
	union select'Scotland','United Kingdom'
	union select'Siberia','Russia'
	union select'Slavakia','Slovakia'
	union select'Slovak Republic','Slovakia'
	union select'Slovaquie','Slovakia'
	union select'Slovechno','Slovakia'
	union select'Soviet Russia Union','FSU'
	union select'Russland ehem.SU','Russia'
	union select'Ehem UdssR','FSU'
	union select'Soviet Union','FSU'
	union select'Soviet Union (Russia)','Russia'
	union select'Soviet Union, Belorussia','Belarus'
	union select'Soviet Union, Estonia','Estonia'
	union select'Soviet Union, Moldova','Moldova'
	union select'Soviet Union, Russia','Russia'
	union select'Soviet Union, Ukraine','Ukraine'
	union select'Sovjet Union','FSU'
	union select'Sowiet Union','FSU'
	union select'Sowjetunion','FSU'
	union select'SU','FSU'
	union select'swisterland','Switzerland'
	union select'Switzerland','Switzerland'
	union select'SYRIA','Other'
	union select'SZARVOS','Hungary'
	union select'Tajekistan','Tajikistan'
	union select'Tajikistan','Tajikistan'
	union select'Taschkent','Uzbekistan'
	union select'TCHECOLOVAQUIE','Czech Republic'
	union select'TCHECOSLOVAQUIA','Czech Republic'
	union select'Tchecoslovaquie','Czech Republic'
	union select'Tchéquie','Czech Republic'
	union select'The Netherlands','Netherlands'
	union select'Tinca','Romania'
	union select'Tnisie','Tunisia'
	union select'Tolochin','Belarus'
	union select'Tschechia','Czech Republic'
	union select'TUNESIE','Tunisia'
	union select'TUNIS','Tunisia'
	union select'Tunisia Djerba','Tunisia'
	union select'TUNISIE','Tunisia'
	union select'TURKEY','Turkey'
	union select'TURKMENISTAN','Turkmenistan'
	union select'TURQUIE','Turkey'
	union select'UCRAINA','Ukraine'
	union select'Udmurtien  UdSSR','Russia'
	union select'UDSSR','FSU'
	union select'UdSSR Abchasien','Georgia'
	union select'UdSSR Armenien','Armenia'
	union select'UdSSR Littauen','Lithuania'
	union select'UdSSR Moldawien','Moldova'
	union select'UdSSR Region Krim','Ukraine'
	union select'UdSSR RF','Russia'
	union select'UdSSR Turkmenistan','Turkmenistan'
	union select'UdSSR Ukraine','Ukraine'
	union select'UdSSR Ukraine/RF','Ukraine'
	union select'UdSSR Usbekistan','Uzbekistan'
	union select'UdSSR Weissrussland','Belarus'
	union select'UdSSR Wessrussland','Belarus'
	union select'UGANDA','Other'
	union select'Uk','Ukraine'
	union select'Ukaraine','Ukraine'
	union select'Ukarine','Ukraine'
	union select'UKR','Ukraine'
	union select'Ukra','Ukraine'
	union select'Ukraaine','Ukraine'
	union select'Ukrain','Ukraine'
	union select'UKRAINA','Ukraine'
	union select'Ukraine  UdSSR','Ukraine'
	union select'Ukraine  USSR','Ukraine'
	union select'Ukraine (Soviet Union)','Ukraine'
	union select'Ukraine UdSSR','Ukraine'
	union select'Ukraine USSR','Ukraine'
	union select'Ukraine/USSR','Ukraine'
	union select'Ukraune','Ukraine'
	union select'Ukriane','Ukraine'
	union select'Ulraine','Ukraine'
	union select'UNGARIA','Hungary'
	union select'UNITED KINGDOM','United Kingdom'
	union select'United States','Other'
	union select'UNKNOWN','Other'
	union select'Unkraine','Ukraine'
	union select'Ural','Russia'
	union select'Urkaine','Ukraine'
	union select'Uklraine','Ukraine'
	union select'Urshava','Ukraine'
	union select'URSS','FSU'
	union select'US','Other'
	union select'USA','Other'
	union select'Usbekistan','Uzbekistan'
	union select'USSR','FSU'
	union select'USSR Russia','Russia'
	union select'USSR, Moldova','Moldova'
	union select'UsSSR','FSU'
	union select'Uzbekestan','Uzbekistan'
	union select'Uzbekeistan','Uzbekistan'
	union select'Uzbekistan','Uzbekistan'
	union select'VARSOVIE','Poland'
	union select'Veszprem','Hungary'
	union select'Vienna','Austria'
	union select'Vitebsk','Belarus'
	union select'Volinsk','Ukraine'
	union select'Weisrussland','Belarus'
	union select'Weissrus.','Belarus'
	union select'Weissrusland','Belarus'
	union select'Wessrussland','Belarus'
	union select'Weissrussl.','Belarus'
	union select'Weissrussland','Belarus'
	union select'Weissrussland  UdSSR','Belarus'
	union select'Weissrussland UdSSR','Belarus'
	union select'Wessrussl.','Belarus'
	union select'White russia (Polish region)','Belarus'
	union select'Wiesrussland','Belarus'
	union select'YUGOSLAVIA','Other'


	alter table dbo.clients add BirthCountryId int null

	update c set BirthCountryId = bc.id
	from dbo.Clients as c 
	join dbo.BirthCountries as bc on c.PobCountry = bc.Name
	
	update c set birthcountryid = bc.id
	from dbo.clients as c
	join @t2 as t on c.PobCountry = t.a
	join dbo.BirthCountries as bc on c.PobCountry = bc.Name
end