declare @t table (id int, stn nvarchar(400), sn nvarchar(400), l int)
insert into @t values(348, 'Homecare', 'Chore/Housekeeper Services', 3)
insert into @t values(349, 'Homecare', 'Personal/Nursing Care', 3)
insert into @t values(350, 'Homecare', 'Skilled Nursing', 3)
insert into @t values(352, 'Homecare', 'Program Costs', 3)
insert into @t values(353, 'Food Programs', 'Meals-On-Wheels', 3)
insert into @t values(354, 'Food Programs', 'Food Packages', 3)
insert into @t values(355, 'Food Programs', 'Congregate Meals', 3)
insert into @t values(356, 'Food Programs', 'Food Vouchers', 3)
insert into @t values(358, 'Client Transportation', 'Client Transportation', 2)
insert into @t values(360, 'Medical Program', 'Medical Program', 3)
insert into @t values(361, 'Dental Program', 'Dental Program', 2)
insert into @t values(362, 'Medical Equipment', 'Medical Equipment', 3)
insert into @t values(363, 'Medicine', 'Medicine', 3)
insert into @t values(364, 'Minor Home Modifications', 'Minor Home Modifications', 2)
insert into @t values(365, 'Winter Relief', 'Winter Relief', 3)
insert into @t values(366, 'Case Management', 'Personnel', 2)
insert into @t values(367, 'Other Services', 'Respite Care', 2)
insert into @t values(368, 'Medical Program', 'Rehabilitation', 2)
insert into @t values(369, 'Medical Program', 'Psychiatric Care', 2)
insert into @t values(370, 'Medical Program', 'Therapeutic Sessions', 2)
insert into @t values(371, 'Other Services', 'Group Therapy', 2)
insert into @t values(372, 'Other Services', 'Friendly Visitor Program', 2)
insert into @t values(373, 'Other Services', 'Personnel', 2)
insert into @t values(374, 'Other Services', 'Other- Associated Costs By Client.', 2)
insert into @t values(375, 'Other Services', 'Other- Total Cost with Clients Names.', 2)
insert into @t values(376, 'Other Services', 'Other- Total Cost No Names', 2)
insert into @t values(377, 'Socialization', 'Cafe Europa - Materials and Supplies', 2)
insert into @t values(378, 'Socialization', 'Cafe Europa - Food', 2)
insert into @t values(379, 'Socialization', 'Cafe Europa - Entertainment', 2)
insert into @t values(380, 'Socialization', 'Cafe Europa - Client Transportation', 2)
insert into @t values(381, 'Socialization', 'Cafe Europa - Outreach', 2)
insert into @t values(382, 'Socialization', 'Cafe Europa - Rent of Facility (survivor group only)', 2)
insert into @t values(385, 'Socialization', 'Other- Total Cost with Clients Names.', 2)
insert into @t values(386, 'Socialization', 'Other- Total Cost No Names', 2)
insert into @t values(387, 'Administrative Overhead', 'Administrative Overhead', 2)
insert into @t values(388, 'Annual Home Care Assessment', 'Annual Home Care Assessment', 3)
insert into @t values(398, 'Other Services', 'Adult Day Care', 2)
insert into @t values(401, 'Case Management', 'Case Management', 2)
insert into @t values(402, 'Other Services', 'Benefits', 2)
insert into @t values(403, 'Emergency Assistance', 'EAP', 2)
insert into @t values(405, 'Annual Home Care Assessment', 'Annual Home Care Assessment Fee - Do Not Use', 1)
insert into @t values(406, 'Client Transportation', 'Personnel', 2)
insert into @t values(407, 'Food Programs', 'Personnel', 2)
insert into @t values(408, 'Homecare', 'Personnel', 2)
insert into @t values(409, 'Other Services', 'Respite Care- DO NOT USE', 1)
insert into @t values(410, 'Socialization', 'Personnel', 2)
insert into @t values(411, 'Homecare', 'Exceptional Hours 5%', 3)
insert into @t values(412, 'Homecare', 'Exceptional Hours 10%', 3)
insert into @t values(413, 'Other Services', 'Material Support', 3)
insert into @t values(414, 'Other Services', 'Legal Services', 2)
insert into @t values(415, 'Other Services', 'Repair Workshop (Moked)', 2)
insert into @t values(416, 'Other Services', 'Vehicles', 2)
insert into @t values(417, 'Other Services', 'Training', 2)
insert into @t values(418, 'Homecare', 'Exceptional Hours 12%', 3)
insert into @t values(419, 'Other Services', 'Other- Total Cost with Clients Names2', 2)
insert into @t values(420, 'Other Services', 'Other- Total Cost with Clients Names3', 2)
insert into @t values(421, 'Other Services', 'Other- Total Cost with Clients Names', 2)
insert into @t values(422, 'Other Services', 'Other- Total Cost No Names2', 2)
insert into @t values(423, 'Other Services', 'Other- Total Cost No Names3', 2)
insert into @t values(426, 'Socialization', 'Other- Total Cost No Names 2', 2)
insert into @t values(428, 'Medical Program', 'Health Insurance', 2)

update s set ServiceLevel = t.l
from @t as t
join services as s on t.id = s.id