//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CC.Data.DataContext
{
    public partial class AgenciesService
    {
        public int Id { get; set; }
        public int AgencyId { get; set; }
        public int ServiceId { get; set; }
        public bool Allowed { get; set; }
        public System.DateTime InsertedAt { get; set; }
        public int InsertedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual User User { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User1 { get; set; }
    }
    
}
