//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CC.Data.DataContext
{
    public partial class AgencyBudget
    {
        public int Id { get; set; }
        public int BudgetId { get; set; }
        public int AgencyId { get; set; }
        public short ApprovalStatusId { get; set; }
        public string ApprovalRemarks { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Budget Budget { get; set; }
    }
    
}
