//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CC.Data.DataContext
{
    public partial class ClientReport
    {
        public int Id { get; set; }
        public int ServiceReportId { get; set; }
        public int ClientId { get; set; }
        public byte SubServiceTypeId { get; set; }
        public Nullable<int> SubServiceId { get; set; }
        public Nullable<short> ReportedHours { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<byte> Units { get; set; }
        public Nullable<byte> Rate { get; set; }
        public decimal Cost { get; set; }
        public string Currency { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual Client Client { get; set; }
        public virtual ServiceReport ServiceReport { get; set; }
    }
    
}
