//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CC.Data.DataContext
{
    public partial class State
    {
        public State()
        {
            this.AgencyGroups = new HashSet<AgencyGroup>();
            this.Clients = new HashSet<Client>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int CountryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AgencyGroup> AgencyGroups { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual Country Country { get; set; }
    }
    
}
