//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CC.Data
{
    public partial class AgencyGroup
    {
        public AgencyGroup()
        {
            this.Agencies = new HashSet<Agency>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public int CountryId { get; set; }
    
        public virtual ICollection<Agency> Agencies { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
    
}
