//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CC.Data
{
    public partial class Currency
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
    
}
