CREATE TABLE [dbo].[Daf]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[EvaluatorId] int not null,
	[ClientId] int not null,
	[CreatedAt] datetime not null,
	[CreatedBy] int not null,
	[UpdateAt] datetime,
	[UpdatedBy] int,
	[DownloadedAt] datetime null,
	[DownloadedBy] int null,
	[DownloadedTo] varchar(47) null,
	[UploadedAt] datetime null,
	[UploadedBy] int null,
	[UploadedTo] varchar(47) null,
	[UserConsentObtainedAt] datetime,
	[AssessmentDate] datetime,
	[GovernmentHours] shortDec null check (GovernmentHours >= 0),
	[ExceptionalHours] shortDec null check (ExceptionalHours >= 0),
	[AdditionalComments] nvarchar(max),
	[EvaluatorPosition] nvarchar(max),
	[SignedAt] datetime,
	[SignedBy] int,
	[ReviewedBy] int,
	[ReviewedAt] datetime,
	[EffectiveDate] datetime NOT NULL,
	[FunctionalityScoreId] int,
	[StatusId] int not null default(0),
		CONSTRAINT FK_Daf_Statuses FOREIGN KEY (StatusId) REFERENCES DafStatuses(Id),
	[TotlaScore] decimal(9,2) default 0,-- as ([dbo].[fnGetDafTotalScore]([Xml])),
	[Xml] xml,-- (DafStructureXmlSchemaCollection),
	[Rowversion] rowversion,
	[FileName] nvarchar(255),
	[Disclaimer] bit not null default(0),
	constraint FK_daf_createdBy foreign key (CreatedBy) references dbo.users(id),
	constraint FK_daf_updatedBy foreign key (UpdatedBy) references dbo.users(id),
	constraint FK_daf_doenloadedBy foreign key ([DownloadedBy]) references dbo.users(id),
	constraint FK_daf_eval foreign key (EvaluatorId) references dbo.users(id),
	constraint FK_daf_client foreign key (ClientId) references dbo.clients(id),
	constraint FK_daf_rev foreign key (ReviewedBy) references dbo.users(id),
	constraint FK_daf_sig foreign key (SignedBy) references dbo.users(id),
	constraint FK_daf_func foreign key (FunctionalityScoreId) references dbo.FunctionalityScores(Id),
)
go

alter table [Daf]
add constraint con_effectivedate default GETDATE() for [EffectiveDate]
